export const properties = [
    {
      id: '21521551',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1665486018877-b191a802c2c3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDV8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1662987551255-795f53a286ec?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDZ8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1635831233800-abaae2910c39?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDl8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1662987978932-00444d4654e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDd8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: true,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '267864751',
      date: '01-04-2022',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Condo',
      description: 'bla bla bla',
      price: '190000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
        'https://images.unsplash.com/photo-1663334840232-03a3c8631089?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEwfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        galleryImgs: [
          'https://images.unsplash.com/photo-1665512423024-e7ecdc67840a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE0fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1663334840232-03a3c8631089?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEwfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1662987260376-4658985adce1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE4fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
        ],
      hasVideo: false,
      videos: [],
      address: {
        title: '8242 Main St',
        county: 'Boston',
        state: 'MS',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '98685845',
      date: '03-05-1991',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Multi',
      description: 'bla bla bla',
      price: '474000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
        'https://images.unsplash.com/photo-1665095111931-fc4fa813e21c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIwfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        galleryImgs: [
          'https://images.unsplash.com/photo-1665074112792-a3fd50309263?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIyfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1666011740605-b5df1f6fb578?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI0fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1654534099214-4096f25a683b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI5fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
        ],
      hasVideo: false,
      videos: [],
      address: {
        title: '8215 Clerk Av',
        county: 'New York',
        state: 'NY',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '786786889',
      date: '04-22-2006',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Apartment',
      description: 'bla bla bla',
      price: '999000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
        'https://images.unsplash.com/photo-1665516533754-d98825ae07e6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI2fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        galleryImgs: [
          'https://images.unsplash.com/photo-1641948617776-bea2b967a706?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI3fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1654534095007-5db1b4faa1a6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDMwfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1664651834879-b402c0bfc350?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDM3fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
        ],
      hasVideo: false,
      videos: [],
      address: {
        title: '9351 Riscoll Ave',
        county: 'Los Angeles',
        state: 'CA',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '5421551',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1666625376136-ab75a552015c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDJ8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1666625376136-ab75a552015c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDJ8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1666625242696-9a47b6a0d1e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDN8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1666548035757-bf13f58d1635?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDZ8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '93258',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1666625159229-069a7dcffd56?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1666625159229-069a7dcffd56?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1655265171060-21004d02ae3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDl8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1655265171060-21004d02ae3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDl8Ul9GeW4tR3d0bHd8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '424515',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1655265173567-b58b3a59240f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE2fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1655265173567-b58b3a59240f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE2fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1655265172458-7fcc47c40680?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEyfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1544519322-87224bcdf632?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE4fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '12142515',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1544519322-87224bcdf632?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE4fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1659956608657-8d649f07da6b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIwfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1655265172642-551099a82e1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE0fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1649343800236-46d2889a0c4f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIyfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '12142515',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1664237941200-0c9279ccd3a0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIzfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1664237941200-0c9279ccd3a0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIzfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1665761125784-e432f7f8539e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDMwfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1666742813444-f947797527cf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI5fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '32141214',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1666713838610-bbfe08cc930f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI4fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1666713838610-bbfe08cc930f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDI4fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1666155545465-39c112c85e9c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDMzfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1665066358241-d2beeb8d3b32?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDM4fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
    {
      id: '32141214',
      date: '03-05-1997',
      href: '/detail',
      listingCategoryId: 17,
      listingType: 'buy',
      propertyType: 'Townhouse',
      description: 'bla bla bla',
      price: '260000',
      features: {
        bedrooms: 3,
        bathrooms: 2,
        sqft: 431,
        builtIn: '1988',
        hoa: true,
        airCentral: true,
        heat: false,
        smartThermo: false,
        parking: true,
        laundry: true,
        pool: false,
        deck: false,
        balcony: false,
        securityCam: true,
        gym: false,
        petFriendly: false,
        mediaRoom: false,
        communityRoom: true,
        gatedAccess: false,
        storage: false,
        outdoorSpace: false,
        kitchenAppl: false,
        fence: true,
        insWindows: false,
        fireplace: true,
        flooring: true,
        sewer: false,
        basement: true
      },
      featuredImage:
      'https://images.unsplash.com/photo-1665066358241-d2beeb8d3b32?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDM4fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
      galleryImgs: [
        'https://images.unsplash.com/photo-1662987978932-00444d4654e5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDQxfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1635831233800-abaae2910c39?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDQzfFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60',
        'https://images.unsplash.com/photo-1665486018877-b191a802c2c3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDM5fFJfRnluLUd3dGx3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
      ],
      hasVideo: false,
      videos: [],
      address: {
        title: '123 Limestone Ln, Suite #482',
        county: 'Sarasota',
        state: 'FL',
        zipCode: '22141',
        country: 'us',
        latitude: '55.2094559',
        longitude: '61.5594641',
      },
      advertiser: {
        clientAlias: 'Swan Brookers',
        clientId: 9202751408833,
        logo: {
          url: '',
        },
        phone: '954302563',
        typeId: 3,
        urlAlias: 'swan-brokers',
        reviewStart: 4.8,
        reviewCount: 28
      },
      commentCount: 70,
      viewCount: 602,
      like: false,
      isFeatured: false,
      isNew: false,
      isTop: false,
      isVirtualTour: false,
      isSold: false,
      isSchedule: false,
      saleOff: '-10% off',
      isAds: null,
    },
  ];